### ISSUE TITLE
npmignore should include some gitignore entries

### ISSUE THREAD

**Issue by aduth** [Automattic/interpolate-components#4]
An `.npmignore` file is not merged with `.gitignore`, so if present, all desired ignored entries from `.gitignore` should also be present in `.npmignore`, with the exception of `node_modules` (handled by `npm`) and `lib/` (wanted in published package).

Specifically:
- `.DS_Store`
- `/npm-debug.log*`

Otherwise, if log files are present while publishing, they will be included in the published package.

**Comment by gwwar** [comment]
I missed this in the last release, but there was thankfully nothing particularly interesting in my .idea config folder.

https://docs.npmjs.com/cli/publish

```
If both files exist and a file is ignored by .gitignore but not by .npmignore then it will be included. 
```
